name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  playground:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Run Action
        uses: llun/feeds@2.3
        # with:
          # opmlFile: feeds.opml
          # branch: contents
          # Github token for pulling repository information
          # token: # optional, default is ${{ github.token }}
          # Enable custom domain name for the site generator
          # customDomain:
